# Generated by Django 5.2.8 on 2025-11-16 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyMuse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
