# Generated by Django 5.2.8 on 2025-11-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyMuse', '0002_alter_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Defult Title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=models.TextField(),
        ),
    ]
